# Erlang v18.3
#
# docker run --rm pottava/erlang
# docker run --rm -it pottava/erlang erl

FROM alpine:3.4
RUN apk --no-cache add erlang==18.3.2-r0
CMD ["cat", "/usr/lib/erlang/releases/18/OTP_VERSION"]
